project:
  type: website
  output-dir: docs

website:
  title: "Tan Jia Yi, Andrea"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: minty
    # or maybe minty or vapor?
    css: src/styles.css
    toc: true

editor: visual

