project:
  type: website
  output-dir: docs

website:
  title: "Tan Jia Yi, Andrea"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: nm2207.qmd
        text: NM2207

format:
  html:
    theme: minty
    # or maybe minty or vapor?
    css: styles.css
    toc: true

editor: visual

