```{r}
# Packages
library(tidyverse)
library(ggplot2)
library(gsignal)
library(forcats)
```

```{r}
# Importing Cleaned Datasets
labelled_movies <- c("Buddy","Hobbit","Machete","Mitty","Paranormal","Hunger")
#for(i in labelled_movies){assign(i,read_csv(sprintf("./src/data/cleaned/%s_cleaned.csv",i)))}

# Importing Snipped Datasets
for(i in c("ms_data","screen_times")){
  assign(i,read_csv(sprintf("./src/data/cleaned/snipped_%s.csv",i)))
}

# Set factor for Time Column to scale with actual time
ms_data$Time <- factor(ms_data$Time, levels=unique(ms_data$Time))

# Labelled ms_data (Only 6 diff movies)
labelled_ms <- ms_data %>% dplyr::filter(!is.na(label))

tidied_labelled_ms <- labelled_ms %>%
  group_by(movie_F_ind) %>% #To add a counter common to movie duplicates
  mutate(counter = row_number(movie_F_ind)) %>% #To separate labels
  separate_longer_delim(
    cols = label,
    delim = "; "
  ) %>% #To categorise fear and non-fear labels
  mutate(is.fear = if_else(grepl("death|suspense|horror|murder|aggressive|violence|shock",label), "Fear","Others")) %>% #To compile all cmpds in 1 column
  pivot_longer(
    cols = matches("^\\d"),
    names_to = "cmpd",
    values_to = "conc"
  ) %>% #To correct for noise in baseline + Conc per pax
  mutate(conc=if_else(conc<0|is.na(conc), 0,conc),
         conc_perpax = conc/screen_times$number.visitors[movie_F_ind])

# Unlabelled ms_data (Excluding the buffer time before labelled movies start)
unlabelled_ms <- ms_data %>% dplyr::filter(is.na(label) & !grepl(paste(labelled_movies, collapse="|"), movie))
```

```{r}
# Graph 1
# A segmented bar plot of compound concentrations against compound mass labels. Bar plots will be segmented by total % concentration under each fear label. This will allow us to observe which compounds are most commonly present when in fear. Based on the observations, a narrowed list of compounds will be analysed in the later graphs (List A)

#Chosen Colour Palette (TODO)
colour_palette <- c("#a9a9f9","#009699")
colour_gradient <- c("#009699","royalblue","#a9a9f9") #Low to high conc

#Scenes were double-counted if fell under both fear and non-fear scene labels

graph_1 <- tidied_labelled_ms %>% #To introduce %
  group_by(cmpd) %>%
  mutate(Tconc = sum(conc)) %>%
  group_by(cmpd,is.fear) %>%
  mutate(fraction = sum(conc)/Tconc) %>%
  distinct(cmpd,is.fear,fraction) %>%
  arrange(is.fear, desc(fraction))

#For later stuff
fear_cmpd_ranked <- graph_1$cmpd[1:(length(graph_1$cmpd)/2)]

#For user input in shiny (TODO) 
start_rank <- 1
end_rank <- 25

select_to_plot_1 <- graph_1[c(start_rank:end_rank, (length(graph_1$cmpd)-start_rank+1):(length(graph_1$cmpd)-end_rank+1)),]

select_to_plot_1 %>%
  group_by(is.fear) %>%
  mutate(cmpd = fct_reorder(cmpd, fraction)) %>%
  ggplot(aes(y = cmpd, x = fraction, fill = fct_reorder(is.fear, -fraction))) +
  geom_col() + 
  labs(title = paste("Top",start_rank,"to",end_rank,"Most Frequently Emitted Compounds when in Fear"),
       subtitle = "Identified by distribution across different types of scenes",
       y = "m/z of Compound", 
       x = "Fraction of the Total Concentration", 
       fill = "Type of Scene") + 
  scale_fill_manual(values=colour_palette)

#scale_fill_manual(values=c("red","blue")
#scale_x_discrete(guide=guide_axis(angle=90))
#scale_fill_brewer(palette="Set3")
```

```{r}
# Graph 2 (Changed from bar to hex)
# A bar graph displaying the total concentration of a specific chosen compound under each scene label. This will give a clearer idea of the distribution of the selected compound across different types of scenes. This will only be for compounds in List A.

#DOUBLE-COUNTING

#MORE SHINY TASKS: Add info about bin when hover over hex (TODO)

#For user input in Shiny (TODO)
user_cmpd_2 <- "60.0490"
user_cmpd_2 <- "235.1928"

#with 0 --> Highlights that be at 0 and relatively same amount of time (Due to vagueness of scene labels)
tidied_labelled_ms %>% 
  dplyr::filter(cmpd == user_cmpd_2) %>%
  ggplot(aes(x=conc_perpax, y=label)) + 
  geom_hex() +
  labs(title = paste("Distribution of compound with m/z =",user_cmpd_2,"across different scenes"),
       subtitle = "Inclusive of data points where compound is absent",
       y = "Type of Scene", 
       x = "Concentration per Pax per Scene") + 
  scale_fill_gradientn(colours = colour_gradient)
  
#without 0 points --> For better idea of distribution
tidied_labelled_ms %>% 
  dplyr::filter(cmpd == user_cmpd_2, conc>0) %>%
  ggplot(aes(x=conc_perpax, y=label)) + 
  geom_hex() + 
  labs(title = paste("Distribution of compound with m/z =",user_cmpd_2,"across different scenes"),
       subtitle = "Excluding data points where compound is absent",
       y = "Type of Scene", 
       x = "Concentration per Pax perScene") + 
  scale_fill_gradientn(colours = colour_gradient)
```

```{r}
# Graph 3 #REMOVE? USELESS
# Multiple box plots will be plot to display the distribution of a compound's concentration under different scene labels. This will give a clearer idea of the distribution of concentrations, instead of just the total concentration across all similar scenes.  This will only be for compounds in List A.

```

```{r}
# Graph 4 (now 3)
# A line graph for the concentration of a chosen compound against time. The time will reflect the duration into a movie. Meanwhile, the list of compounds is once again restricted to List A. Multiple graphs will be either faceted or overlaid to observe the trend for the different compounds in the same movie. Scenes/Points with fear labels will be highlighted.

# Other Shiny (TODO): Hover over facet for a zoom in

#For user input in Shiny (TODO)
user_movie_3 <- "The Hobbit: The Desolation of Smaug"
user_top_cmpd_3 <- 10 #A range selected by user
user_bottom_cmpd_3 <- 15
user_count_cmpd_3 <- user_bottom_cmpd_3 - user_top_cmpd_3 + 1

#Vector of selected compounds
selected_cmpd_3 <- top_fear_cmpd[user_top_cmpd_3:user_bottom_cmpd_3]

graph_3 <- tidied_labelled_ms %>% arrange(is.fear) %>%
  distinct(Time, cmpd, .keep_all = TRUE) %>% #To remove expanded labels
  arrange(counter, cmpd) %>% 
  dplyr::filter(cmpd %in% selected_cmpd_3) %>% #Select top cmpd
  dplyr::filter(movie==user_movie_3)  %>% #Select 1 movie
  group_by(counter,cmpd) %>% #To add an ave conc common to similar movies
  mutate(average = mean(conc_perpax)) %>% ungroup()

# Set a list of cmpd to remove (Complete Absence)
removed_cmpd <- graph_3 %>% pivot_wider(
  names_from = "cmpd",
  values_from = "conc",
  id_cols="Time"
) %>% select_if(function(x){all(x==0) & is.numeric(x)}) %>% colnames()

# Plot
graph_3 %>% 
  dplyr::filter(cmpd != removed_cmpd) %>% 
  transform(cmpd=factor(cmpd, levels=selected_cmpd_3)) %>%
  arrange(cmpd) %>% #To look at only 1 movie duration
  distinct(counter, cmpd, .keep_all = TRUE) %>% #NOTE: IF PLOT CONC, A FEW COMPLETE ABSENCE
  ggplot(aes(x=Time, y=average, colour=is.fear)) + 
  geom_point() + facet_wrap(~ cmpd, ncol = floor(sqrt(user_count_cmpd_3)), scales="free", labeller = as_labeller(~ paste0("No. ", which(selected_cmpd_3 %in% .x),":\n", .x))) + 
  labs(title = paste("Distribution of Top", user_top_cmpd_3, "to", user_bottom_cmpd_3, "Fear Compounds in", user_movie_3),
       subtitle = "Concentrations are averaged",
       y = "Concentration per Scene", 
       x = "Duration of Movie",
       caption = paste(if_else(length(removed_cmpd)>1, "Plots", "Plot"), 
                       "for",
                       if_else(length(removed_cmpd)>1, "compounds", "compound"),
                       "with m/z =",
                       paste(removed_cmpd, collapse=", "), 
                       if_else(length(removed_cmpd)>1, "have", "has"),
                       "been removed due to absence throughout movie.")) + 
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.text = element_text(size=5, margin=margin(t=1,b=2))) +
  scale_color_manual(values = colour_palette) + expand_limits(y = 0)
```

```{r}
# Graph 5
# For a chosen compound, different screenings of the same movie are selected and the concentration of that compound against time is plot and overlaid for the different screenings. These screenings will be selected according to a criteria set by the user, such that the other variables for those screenings are relatively similar. This allows us to observe for any trends between the compound emission and factors such as the time of day, type of fear, and the influence of people.

```

```{r}
# Graph 6
# For the top fear compounds determined, their average emission will be tabulated for different movies, throughout the movie and across multiple screenings. This emission intensity will be plot against the online fear ratings for these movies to give an idea of whether the online ratings are an accurate reflection of our chemical reflection, vice versa.
```

# Old Graphs/Code
```{r eval=FALSE}
#Graph 2 average values --> Did not work out since lots of 0
graph_2 <- tidied_labelled_ms %>% #To ave conc per scene
  dplyr::filter(cmpd == user_cmpd_2) %>%
  group_by(label) %>%
  mutate(average = mean(conc)) %>%
  distinct(label,average, cmpd) %>%
  arrange(desc(average))
  
graph_2 %>%
  ggplot(aes(y = average, x = label)) +
  geom_col() + 
  labs(title = paste("Distribution of Compound of m/z =",user_cmpd_2,"across different scene labels"),
       subtitle = "For scenes with more than 1 label assigned, concentrations were double-counted",
       y = "Average Concentration per Scene", 
       x = "Type of Scene") + 
  scale_x_discrete(guide=guide_axis(angle=90))
```
